create sequence view_seq start with 1 increment by 50
create table video (duration float(53), code bigint generated by default as identity, description varchar(255), title varchar(255), primary key (code))
create table view (age integer, id bigint not null, start_playing_time timestamp(6), video_code bigint, user_full_name varchar(255), primary key (id))
alter table if exists view add constraint FK299yhpw1gwatw9r5hl75n1pq6 foreign key (video_code) references video